name: Toilet Fan Off Scheduler

on:
  schedule:
    - cron: '*/5 * * * *' # 5分ごとに実行
  workflow_dispatch: # 手動実行も可能

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Execute scheduler
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SWITCHBOT_API_TOKEN: ${{ secrets.SWITCHBOT_API_TOKEN }}
          SWITCHBOT_API_SECRET: ${{ secrets.SWITCHBOT_API_SECRET }}
          SWITCHBOT_BOT_TOILET_FAN_DEVICE_ID: ${{ secrets.SWITCHBOT_BOT_TOILET_FAN_DEVICE_ID }}
        run: npm start 